branches: master

pipeline:
  build:
    image: ruby
    commands:
      - curl -L https://github.com/ly95/lanyon/archive/v1.0.0.tar.gz | tar zx
      - rm -rf lanyon-1.0.0/_posts
      - cp -r _posts lanyon-1.0.0
      - cp -r _my_tags lanyon-1.0.0
      - bundle install --path lanyon-1.0.0
      - bundle exec jekyll build -s lanyon-1.0.0
  publish:
    image: plugins/gh-pages
    secrets: [ github_username, github_password ]
    pages_directory: _site/
