version: 2
jobs:
  deploy:
    docker:
      - image: circleci/ruby:2.4.3-node-browsers
    steps:
      - checkout
      - run: curl -L https://github.com/ly95/lanyon/archive/v1.0.0.tar.gz | tar zx
      - run: rm -rf lanyon-1.0.0/_posts
      - run: cp -r _posts lanyon-1.0.0
      - run: cp -r _my_tags lanyon-1.0.0
      - run: cd lanyon-1.0.0
      - run: bundle install
      - run: bundle exec jekyll build
workflows:
  version: 2
  build:
    jobs:
      - deploy
