version: 2

jobs:
  deploy:
    docker:
      - image: circleci/ruby:2.4.3-node-browsers
    steps:
      - checkout
      - run: |
          curl -L https://codeload.github.com/ly95/lanyon/zip/master -o lanyon-master.zip
          unzip lanyon-master.zip
          rm -rf lanyon-master/_posts
          cp -r _posts lanyon-master
          cp -r _my_tags lanyon-master
          cd lanyon-master
          bundle install
          bundle exec jekyll build
      - run: bash .circleci/deploy-ghpages.sh

workflows:
  version: 2
  build:
    jobs:
      - deploy
